#cloud-config
repo_update: true
repo_upgrade: all

packages:
 - docker
 - git

runcmd:
 - service docker start
 - touch /var/run/docker.sock
 - [ sh, -c, "usermod -a -G docker ec2-user" ]
 - [ sh, -c, "chown -R ec2-user:docker /var/run/docker.sock" ]
 - [ sh, -c, "mkdir -p /home/ec2-user/data" ]
 - [ sh, -c, "docker run -dit --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /home/ec2-user/data:/data -e CHE_PORT=80 -e CHE_DOCKER_IP_EXTERNAL=$(curl http://169.254.169.254/latest/meta-data/public-ipv4) eclipse/che start"]